version: "3.7"
services:
    
    jupyter-spark:
        image: disynet/asme:latest
        networks:
            - default_net
        ports:
          - "8888:8888"
          - "4040-4080:4040-4080"
        environment: 
          - JUPYTER_ENABLE_LAB=yes
        volumes:
          - ./notebooks:/home/jovyan/work/notebooks/
          - ./data:/home/jovyan/work/data

networks:
    default_net:
      attachable: true